name: Yuwen Huang, Essie
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-primer

navigation:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/about/"
  - text: "Blog"
    url: "/blog/"
  - text: "CV"
    url: "/cv/"
